# Generated by Django 4.2.2 on 2023-07-24 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tguser',
            options={'verbose_name': 'Телеграмм-пользователь', 'verbose_name_plural': 'Телеграмм-пользователи'},
        ),
    ]
